config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  resources :cocktails, only: [:index, :show, :edit, :new, :create, :update, :destroy] do
    resources :doses, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, presence: true
  validates :cocktail, presence: true
  validates :ingredient, presence: true
  validates :cocktail_id, uniqueness: { scope: :ingredient_id }
  belongs_to :cocktail
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
  has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
     redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(cocktail_params)
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private
  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @ingredient = Ingredient.find(params[:dose][:ingredient_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    @dose.ingredient = @ingredient
    @dose.save!
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.find(params[:cocktail_id])
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private
  def dose_params
    params.require(:dose).permit(:description, :ingredient, :cocktail)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>


<hr>
  <%= link_to "Go back to cocktails list", cocktails_path %>

app/views/cocktails/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Update your cocktail</title>
</head>
<body>
  <div class="perso-hero">
    <div class="container">
      <h1><%= @cocktail.name %></h1>
      <p>Update Your cocktail</p>
    </div>
  </div>

  <div class="container">
    <div>
      <h3>Update your cocktail</h3>
      <%= render 'cocktails/form' %>
    </div>
    <div>
    <%= link_to "Cocktail Updated", cocktail_path(@cocktail), method: :patch %>
    </div>
  </div>
</body>
</html>

app/views/cocktails/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>
  <div class="hero">
    <div class="container">
      <h1 class="animate__animated animate__bounce">The Best Cocktails in Town</h1>
      <p>Find cocktails inspiration</p>
    </div>
  </div>

  <div class="container text-center">
    <h1 class="text-center">All Cocktails</h1>
    <br>
    <br>
    <div class="add-cocktail">
      <%= link_to "Add your favorite cocktail recipe", new_cocktail_path %>
    </div>
  </div>
  </div>


  <div class="container-bis">
    <div class="cards">
      <div class="cards">
        <% @cocktails.each do |cocktail| %>
          <div class="cards">
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path cocktail.photo.key, height: 300, width: 400, crop: :fill %>')">
              <%= link_to cocktail.name, cocktail_path(cocktail) %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <hr>


</body>
</html>

    <!-- <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">

    </div> -->

app/views/cocktails/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>
  <div class="hero">
    <div class="container">
      <h1>The Best Cocktails in Town</h1>
      <p>Find cocktails inspiration</p>
    </div>
  </div>

  <div class="container">
    <h1>Add a new Cocktail</h1>
    <%= render 'form' %>
  </div>
</body>
</html>

app/views/cocktails/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>
  <div class="hero">
    <div class="container">
      <h1><%= @cocktail.name %></h1>
      <p>Your cocktail</p>
    </div>
  </div>

  <div class="container">


    <%= cl_image_tag @cocktail.photo.key, width: 500, height: 400, crop: :fill %>



    <ul>
      <% @cocktail.doses.each do |dose| %>
      <li><%= dose.ingredient.name %></li>
      <li><%= dose.description %></li>
      <%= link_to "Delete Dose", cocktail_dose_path(dose), method: :delete, data: { confirm: "Are you sure you want to delete your cocktail?"} %>
      <% end %>
    </ul>

        <h3>Add Doses & Ingredients</h3>

        <%= simple_form_for [@cocktail, @dose] do |f| %>
          <%= f.input :description %>
          <%= f.association :ingredient %>
          <%= f.submit %>
        <% end %>

    <%= link_to "Update Cocktail", edit_cocktail_path(@cocktail) %>
    <%= link_to "Delete Cocktail", cocktail_path(@cocktail), method: :delete, data: { confirm: "Are you sure you want to delete your cocktail?"} %>
    <hr>
    <%= link_to "Go back to cocktails list", cocktails_path %>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<!--     <#%= render 'components/navbar' %> -->
    <%= yield %>
<!--   <#%= render 'components/footer' %> -->
  </body>
</html>